language: java

jdk:
  - oraclejdk8

env:
  global:
    - TESTENV_BROKER_URL=https://ws.15xr.msb.oss.cell.vfk.fraunhofer.de/
    - TESTENV_SO_URL=https://so.15xr.msb.oss.cell.vfk.fraunhofer.de/
    - TESTENV_FLOW_URL=https://flow.15xr.msb.oss.cell.vfk.fraunhofer.de/

cache:
  directories:
    - $HOME/.m2

install: true

script:
  - mvn clean install -DskipITs
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: releases
  api_key: ${GH_TOKEN}
  file:
    - msb-client-api/target/msb-client-api-$project_version.jar
    - msb-client-websocket/target/msb-client-websocket-$project_version.jar
  skip_cleanup: true
  on:
    tags: true
  name: $project_version
