language: java

jdk:
  - oraclejdk8
  - oraclejdk11
  - openjdk10
  - openjdk11

env:
  global:
    - TESTENV_BROKER_URL=https://ws.15xr.msb.oss.cell.vfk.fraunhofer.de/
    - TESTENV_SO_URL=https://so.15xr.msb.oss.cell.vfk.fraunhofer.de/
    - TESTENV_FLOW_URL=https://flow.15xr.msb.oss.cell.vfk.fraunhofer.de/

script:
  - mvn test -B

deploy:
  provider: releases
  api_key: ${GH_TOKEN}
  file:
    - msb-client-api/target/msb-client-api-$project_version.jar
    - msb-client-websocket/target/msb-client-websocket-$project_version.jar
  skip_cleanup: true
  on:
    tags: true
  name: $project_version
